"""Added refresh token to table

Revision ID: 6a9fa43e44c0
Revises: 309edcb2ec3e
Create Date: 2025-07-03 16:52:32.712553

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6a9fa43e44c0'
down_revision: Union[str, None] = '309edcb2ec3e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('refresh_token', sa.String(length=255), nullable=True))
    op.drop_column('users', 'token')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('token', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    op.drop_column('users', 'refresh_token')
    # ### end Alembic commands ###
