"""Recipe/RecipeIngredient update

Revision ID: de6cc2de91c6
Revises: 460407338944
Create Date: 2025-06-17 20:19:33.926821

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'de6cc2de91c6'
down_revision: Union[str, None] = '460407338944'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('recipeIngredients', sa.Column('measure', sa.String(length=100), nullable=True))
    op.add_column('recipes', sa.Column('time', sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('recipes', 'time')
    op.drop_column('recipeIngredients', 'measure')
    # ### end Alembic commands ###
